-- Model-Agnostic Personalization Layer
-- Enables transferring personality across base models
-- Part of the "Immortal Soul" architecture

-- ===========================================
-- PERSONALITY PROFILES (Behavioral Signatures)
-- Model-agnostic personality extraction
-- ===========================================
CREATE TABLE IF NOT EXISTS personality_profiles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL,
  
  -- Core style analysis (extracted from training pairs)
  style_analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Example structure:
  -- {
  --   "voice": { "humor_style": "dry", "formality": 0.3, "emoji_usage": "never" },
  --   "vocabulary": { "preferred_terms": [], "avoided_terms": [], "domain_affinity": [] },
  --   "sentence_structure": { "avg_length": 15, "complexity": 0.6 },
  --   "punctuation_patterns": { "em_dash_frequency": 0.2, "oxford_comma": true }
  -- }
  
  -- Natural language behavioral rules
  constitutional_rules text[] DEFAULT ARRAY[]::text[],
  -- Example: ["Always acknowledge uncertainty when speculating", "Prefer concrete examples"]
  
  -- Vocabulary fingerprint
  vocabulary_signature jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Example:
  -- {
  --   "high_frequency": ["fundamentally", "essentially"],
  --   "avoided": ["basically", "like"],
  --   "domain_specific": { "physics": 0.3, "software": 0.5 }
  -- }
  
  -- Topic dispositions (how the user engages with different subjects)
  topic_dispositions jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Example: { "politics": "avoidant", "technology": "enthusiastic" }
  
  -- Extraction metadata
  source_pair_count int NOT NULL,         -- How many training pairs were analyzed
  source_feedback_count int DEFAULT 0,    -- How many feedback entries were analyzed
  confidence_score float DEFAULT 0.5,     -- Higher = more data, more reliable profile
  
  -- Versioning for evolution tracking
  version int NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  
  extracted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS personality_profiles_user_idx ON personality_profiles(user_id);
CREATE INDEX IF NOT EXISTS personality_profiles_active_idx ON personality_profiles(user_id) WHERE is_active = true;

-- ===========================================
-- DISTILLATION PAIRS (Knowledge Transfer)
-- Synthetic training data from old model
-- ===========================================
CREATE TABLE IF NOT EXISTS distillation_pairs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL,
  
  -- The prompt used to generate the response
  prompt text NOT NULL,
  
  -- Response generated by the source model (personality-infused)
  response text NOT NULL,
  
  -- Which model generated this (for lineage)
  source_model_id text NOT NULL,
  source_export_id uuid REFERENCES training_exports(id),
  
  -- Quality metrics
  quality_score float DEFAULT 0.5,        -- Auto-evaluated quality
  style_consistency_score float,          -- How well it matches personality profile
  
  -- Prompt categorization (for diverse coverage)
  prompt_category text,                   -- e.g., "emotional", "factual", "creative", "edge_case"
  
  -- Usage tracking
  used_in_migration uuid,                 -- Which migration used this pair
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS distillation_pairs_user_idx ON distillation_pairs(user_id);
CREATE INDEX IF NOT EXISTS distillation_pairs_source_idx ON distillation_pairs(user_id, source_model_id);
CREATE INDEX IF NOT EXISTS distillation_pairs_unused_idx ON distillation_pairs(user_id) WHERE used_in_migration IS NULL;
CREATE INDEX IF NOT EXISTS distillation_pairs_quality_idx ON distillation_pairs(user_id, quality_score DESC);

-- ===========================================
-- MODEL MIGRATIONS (Transfer Tracking)
-- Tracks model-to-model transfers
-- ===========================================
CREATE TABLE IF NOT EXISTS model_migrations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL,
  
  -- Source model (what we're migrating FROM)
  source_model_id text NOT NULL,
  source_export_id uuid REFERENCES training_exports(id),
  
  -- Target model (what we're migrating TO)
  target_base_model text NOT NULL,        -- e.g., "meta-llama/Llama-4-8B-Instruct"
  target_export_id uuid REFERENCES training_exports(id),  -- Filled after training completes
  
  -- Migration configuration
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- {
  --   "distillation_count": 5000,
  --   "include_raw_pairs": true,
  --   "include_dpo": true,
  --   "quality_threshold": 0.7
  -- }
  
  -- Data used in migration
  distillation_pair_count int DEFAULT 0,
  training_pair_count int DEFAULT 0,
  dpo_pair_count int DEFAULT 0,
  
  -- Status tracking
  status text DEFAULT 'pending',          -- pending → distilling → training → validating → completed | failed
  phase text DEFAULT 'init',              -- Current phase for progress tracking
  
  -- Validation metrics (A/B comparison)
  validation_metrics jsonb DEFAULT '{}'::jsonb,
  -- {
  --   "style_similarity": 0.85,
  --   "user_preference_rate": 0.7,
  --   "a_b_comparisons": 100
  -- }
  
  -- Timestamps
  started_at timestamp with time zone,
  distillation_completed_at timestamp with time zone,
  training_completed_at timestamp with time zone,
  validation_completed_at timestamp with time zone,
  completed_at timestamp with time zone,
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS model_migrations_user_idx ON model_migrations(user_id);
CREATE INDEX IF NOT EXISTS model_migrations_status_idx ON model_migrations(user_id, status);

-- ===========================================
-- DIVERSE PROMPT CORPUS (For Distillation)
-- Pre-generated prompts for comprehensive personality capture
-- ===========================================
CREATE TABLE IF NOT EXISTS prompt_corpus (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- Prompt content
  prompt text NOT NULL,
  
  -- Categorization
  category text NOT NULL,                 -- emotional, factual, creative, philosophical, edge_case, etc.
  subcategory text,                       -- More specific classification
  difficulty text DEFAULT 'medium',       -- easy, medium, hard (complexity)
  
  -- Source
  source text DEFAULT 'generated',        -- generated, curated, user_derived
  
  -- Metadata
  metadata jsonb DEFAULT '{}'::jsonb,
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS prompt_corpus_category_idx ON prompt_corpus(category);

-- ===========================================
-- FUNCTIONS
-- ===========================================

-- Get the latest active personality profile
CREATE OR REPLACE FUNCTION get_personality_profile(p_user_id uuid)
RETURNS jsonb
LANGUAGE sql STABLE
AS $$
  SELECT jsonb_build_object(
    'id', id,
    'style_analysis', style_analysis,
    'constitutional_rules', constitutional_rules,
    'vocabulary_signature', vocabulary_signature,
    'topic_dispositions', topic_dispositions,
    'confidence_score', confidence_score,
    'source_pair_count', source_pair_count,
    'extracted_at', extracted_at
  )
  FROM personality_profiles
  WHERE user_id = p_user_id AND is_active = true
  ORDER BY extracted_at DESC
  LIMIT 1;
$$;

-- Get migration readiness stats
CREATE OR REPLACE FUNCTION get_migration_readiness(p_user_id uuid)
RETURNS jsonb
LANGUAGE sql STABLE
AS $$
  SELECT jsonb_build_object(
    'training_pairs', (SELECT count(*) FROM training_pairs WHERE user_id = p_user_id),
    'feedback_logs', (SELECT count(*) FROM feedback_logs WHERE user_id = p_user_id),
    'preference_pairs', (SELECT count(*) FROM preference_pairs WHERE user_id = p_user_id),
    'distillation_pairs', (SELECT count(*) FROM distillation_pairs WHERE user_id = p_user_id AND used_in_migration IS NULL),
    'has_personality_profile', (SELECT exists(SELECT 1 FROM personality_profiles WHERE user_id = p_user_id AND is_active = true)),
    'active_migrations', (SELECT count(*) FROM model_migrations WHERE user_id = p_user_id AND status NOT IN ('completed', 'failed'))
  );
$$;

-- Mark distillation pairs as used in a migration
CREATE OR REPLACE FUNCTION mark_distillation_used(p_migration_id uuid, p_pair_ids uuid[])
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
  rows_updated int;
BEGIN
  UPDATE distillation_pairs
  SET used_in_migration = p_migration_id
  WHERE id = ANY(p_pair_ids);
  
  GET DIAGNOSTICS rows_updated = ROW_COUNT;
  RETURN rows_updated;
END;
$$;

-- Deactivate old personality profiles when new one is created
CREATE OR REPLACE FUNCTION deactivate_old_profiles()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE personality_profiles
  SET is_active = false
  WHERE user_id = NEW.user_id AND id != NEW.id AND is_active = true;
  RETURN NEW;
END;
$$;

CREATE TRIGGER personality_profile_deactivate_trigger
AFTER INSERT ON personality_profiles
FOR EACH ROW
EXECUTE FUNCTION deactivate_old_profiles();

-- ===========================================
-- SEED: Initial Diverse Prompt Corpus
-- ===========================================
INSERT INTO prompt_corpus (prompt, category, subcategory, difficulty) VALUES
-- Emotional
('How do you feel about failure and setbacks?', 'emotional', 'introspection', 'medium'),
('What brings you genuine joy?', 'emotional', 'positive', 'easy'),
('How do you handle disappointment?', 'emotional', 'coping', 'medium'),
('Describe a moment that changed your perspective on life.', 'emotional', 'transformation', 'hard'),
('What does home mean to you?', 'emotional', 'belonging', 'medium'),

-- Philosophical
('What do you think happens after we die?', 'philosophical', 'existential', 'hard'),
('Is free will an illusion?', 'philosophical', 'metaphysics', 'hard'),
('What makes a life meaningful?', 'philosophical', 'meaning', 'medium'),
('How do you reconcile ambition with contentment?', 'philosophical', 'balance', 'hard'),
('What is the relationship between suffering and growth?', 'philosophical', 'wisdom', 'hard'),

-- Creative
('Write a short poem about the color blue.', 'creative', 'poetry', 'medium'),
('If you were a season, which would you be and why?', 'creative', 'metaphor', 'easy'),
('Describe a perfect day in an alternate universe.', 'creative', 'imagination', 'medium'),
('Tell me a story in exactly three sentences.', 'creative', 'constraint', 'medium'),
('What would you name a star and why?', 'creative', 'naming', 'easy'),

-- Factual/Explanatory
('Explain quantum entanglement to a curious child.', 'factual', 'explanation', 'hard'),
('What is your understanding of how memory works?', 'factual', 'science', 'medium'),
('How would you describe the internet to someone from 1950?', 'factual', 'analogy', 'medium'),
('What is the most important invention in human history?', 'factual', 'opinion', 'medium'),
('How does compound interest work?', 'factual', 'finance', 'easy'),

-- Personal/Advice
('What advice would you give to your younger self?', 'personal', 'reflection', 'medium'),
('How do you approach making difficult decisions?', 'personal', 'process', 'medium'),
('What is your biggest regret?', 'personal', 'introspection', 'hard'),
('How do you stay motivated during difficult times?', 'personal', 'resilience', 'medium'),
('What habits have most improved your life?', 'personal', 'growth', 'easy'),

-- Edge Cases / Unusual
('Why is the sky not purple?', 'edge_case', 'unusual_framing', 'medium'),
('Convince me that silence is a sound.', 'edge_case', 'paradox', 'hard'),
('What would you say to someone who believes nothing is real?', 'edge_case', 'philosophical_challenge', 'hard'),
('How would you describe the taste of water?', 'edge_case', 'ineffable', 'hard'),
('Is it possible to think about nothing?', 'edge_case', 'meta', 'medium'),

-- Social/Relational
('What makes a good friend?', 'social', 'relationships', 'easy'),
('How do you handle conflict in relationships?', 'social', 'conflict', 'medium'),
('What do you think about small talk?', 'social', 'communication', 'easy'),
('How do you know when to trust someone?', 'social', 'trust', 'medium'),
('What is the hardest thing about being understood?', 'social', 'connection', 'hard'),

-- Humor/Wit
('Tell me something that is both true and absurd.', 'humor', 'wit', 'medium'),
('What is the funniest thing about being human?', 'humor', 'observation', 'medium'),
('Make an argument for why Mondays are actually the best day.', 'humor', 'contrarian', 'easy'),
('What would a fish think about rain?', 'humor', 'perspective', 'easy'),
('Why do we press harder on the remote when we know the batteries are weak?', 'humor', 'observation', 'easy')

ON CONFLICT DO NOTHING;

