-- Phase B: Continuous Editor Agent
-- Queue of proactive messages generated by the Editor for Author delivery

CREATE TABLE IF NOT EXISTS editor_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL
    CHECK (message_type IN ('proactive_question', 'gap_alert', 'contradiction_alert', 'feedback_request', 'system_note')),
  priority TEXT NOT NULL DEFAULT 'medium'
    CHECK (priority IN ('low', 'medium', 'high')),
  delivered BOOLEAN NOT NULL DEFAULT FALSE,
  delivered_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_editor_messages_user_undelivered
  ON editor_messages(user_id, delivered, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_editor_messages_user_priority
  ON editor_messages(user_id, priority, created_at DESC);

COMMENT ON TABLE editor_messages IS 'Queued proactive messages from Editor to Author';
